# Generated by roxytest: Do not edit by hand!

# File R/centrality.R: @testexamples

test_that("Function edge_closeness() @ L194", {
  
  (ec <- edge_closeness(ison_adolescents))
  plot(ec)
  ison_adolescents %>% 
    activate(edges) %>% mutate(weight = ec) %>% 
    autographr()
  expect_s3_class(ec, "node_measure")
  expect_length(ec, graph_edges(ison_adolescents))
  expect_equal(unname(ec[1:3]), c(0.562,0.692,0.600), tolerance = 0.001)
})

