test_that("is tests work", {
  expect_true(is_twomode(ison_southern_women))
  expect_false(is_directed(ison_southern_women))
  expect_false(is_weighted(ison_southern_women))
  expect_true(is_weighted(mpn_ryanair))
  expect_true(is_labelled(ison_southern_women))
  expect_true(is_connected(ison_southern_women))
  expect_false(is_complex(ison_southern_women))
  expect_true(is_graph(ison_southern_women))
  expect_true(is_migraph(ison_southern_women))
  expect_true(is_graph(ison_brandes))
  expect_false(is_directed(as_network(ison_southern_women)))
})
